// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdaxssasxgjdznzzucbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkYXhzc2FzeGdqZHpuenp1Y2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTUyNTMsImV4cCI6MjA2NzE3MTI1M30.CMI4zmomijLVm9_MTNz1oUNULAFGDP8UTu4bl89MkMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});